name       : haskell-utf8-string
version    : 1.0.2
release    : 5
source     :
    - https://hackage.haskell.org/package/utf8-string-1.0.2/utf8-string-1.0.2.tar.gz : ee48deada7600370728c4156cb002441de770d0121ae33a68139a9ed9c19b09a
license    : BSD-3-Clause
component  : programming.haskell
summary    : A UTF8 layer for Strings. The utf8-string package provides operations for encoding UTF8 strings to Word8 lists and back, and for reading and writing UTF8 without truncation.
description: |
    A UTF8 layer for Strings. The utf8-string package provides operations for encoding UTF8 strings to Word8 lists and back, and for reading and writing UTF8 without truncation.
builddeps  :
    - ghc-devel
rundeps    :
    - devel :
        - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
