name       : haskell-utf8-string
version    : 1.0.1.1
release    : 2
source     :
    - http://hackage.haskell.org/package/utf8-string-1.0.1.1/utf8-string-1.0.1.1.tar.gz : fb0b9e3acbe0605bcd1c63e51f290a7bbbe6628dfa3294ff453e4235fbaef140
license    : BSD-3-Clause
component  : programming.haskell
summary    : A UTF8 layer for Strings. The utf8-string package provides operations
    for encoding UTF8 strings to Word8 lists and back, and for reading and writing
    UTF8 without truncation.
description: "A UTF8 layer for Strings. The utf8-string package provides operations\
    \ for encoding UTF8 strings to Word8 lists and back, and for reading and writing\
    \ UTF8 without truncation. \n"
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    sed -i "s|4.9|4.11|" utf8-string.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
